name: preloved_mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # Network & API
  http: ^1.2.2
  
  # Media & Files
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Localization & Formatting
  intl: ^0.19.0
  
  # Database
  sqflite: 2.3.3+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true