name: preloved_mobile_app
description: "Aplikasi Jual Beli Barang Bekas (Preloved)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # --- DATABASE LOKAL (HIVE) ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # --- LAINNYA ---
  http: ^1.2.1
  image_picker: ^1.1.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # --- GENERATOR KODE ---
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true