name: preloved_mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # SQLite Database 
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Image Picker
  image_picker: ^1.0.4
  
  # HTTP & API
  http: ^1.1.0
  
  # Date Formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/
  #   - icons/
  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700